### PR TITLE
update problem sets

### PR DESCRIPTION
**Pull request by wupeifan**
It would be great if I can have access to this repo... Otherwise. I have to fork, change, and then merge...

### CODE REVIEW

**Comment by wupeifan** [comment]
@jlperla

**Comment by jlperla** [comment]
Thanks @wupeifan   Does this have chances to the Q8 with the `x2` etc.?  Makes sense to get those all updated at once so we don't have multiple PRs.

**Review by jlperla — APPROVED** [review]
Looks good.

**Comment by jlperla** [comment]
@sglyon  @cc7768  If you guys get a chance, can you do a quick check and approve?  We want to merge in the problem sets so they can launch from the website.  Maybe after this big check, arnav/peifan and I will merge ourselves so we can iterate on problem sets quickly over the term.

**Comment by wupeifan** [comment]
@sglyon @cc7768 This PR is now synchronized with the source code one. It would be great if both can be approved as the first problem set will be due next week...

**Pull request merged**
